packages:
  - auth
  - chain-indexer
  - chain-reader
  - chain-service
  - '*/'

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - nestjs-grpc
  - prisma
  - protobufjs
