syntax = "proto3";

package user;


service UserService {
  rpc GetUserById(GetUserByIdRequest) returns (GetUserByIdResponse);
  rpc GetUserByEmail(GetUserByEmailRequest) returns (GetUserByEmailResponse);
}

message GetUserByIdRequest {
  string id = 1;
}

message GetUserByIdResponse {
  bool success = 1;
  User user = 2;
}

message GetUserByEmailRequest {
  string email = 1;
}

message GetUserByEmailResponse {
  bool success = 1;
  User user = 2;
}

message User {
  string id = 1;
  string email = 2;
  string first_name = 3;
  string last_name = 4;
  string phone_number = 5;
  string avatar = 6;
  bool is_verified = 7;
  string role = 8;
  string created_at = 9;
  string updated_at = 10;
}
